services:
  llm:
    network_mode: "host"
    build:
      context: .
      dockerfile: ./docker/llm/Dockerfile
    ports:
      - "11434:11434"

  # Agent: UI that allows users to interact with the LLM and manage their tasks.
  # It provides a user-friendly interface for users to input their queries, view results, and manage their tasks effectively.
  agent:
    network_mode: "host"

    build:
      context: .
      dockerfile: ./docker/agent/Dockerfile

  # Runner: A RESTful service that executes the tasks defined by the agent.
  runner_app:
    network_mode: "host"
    build:
      context: .
      dockerfile: ./docker/runner_app/Dockerfile
  runner_db:
    env_file:
      - ./docker/runner_db/.env
    network_mode: "host"
    image: mysql